
package cl.iplacex.jam.credito.wssoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CalculoRiesgoImplService", targetNamespace = "http://jam.iplacex.cl/", wsdlLocation = "http://localhost:8080/credito/credito-soap?wsdl")
public class CalculoRiesgoImplService
    extends Service
{

    private static final URL CALCULORIESGOIMPLSERVICE_WSDL_LOCATION;
    private static final WebServiceException CALCULORIESGOIMPLSERVICE_EXCEPTION;
    private static final QName CALCULORIESGOIMPLSERVICE_QNAME = new QName("http://jam.iplacex.cl/", "CalculoRiesgoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/credito/credito-soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULORIESGOIMPLSERVICE_WSDL_LOCATION = url;
        CALCULORIESGOIMPLSERVICE_EXCEPTION = e;
    }

    public CalculoRiesgoImplService() {
        super(__getWsdlLocation(), CALCULORIESGOIMPLSERVICE_QNAME);
    }

    public CalculoRiesgoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULORIESGOIMPLSERVICE_QNAME, features);
    }

    public CalculoRiesgoImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULORIESGOIMPLSERVICE_QNAME);
    }

    public CalculoRiesgoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULORIESGOIMPLSERVICE_QNAME, features);
    }

    public CalculoRiesgoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculoRiesgoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculoRiesgoImpl
     */
    @WebEndpoint(name = "CalculoRiesgoImplPort")
    public CalculoRiesgoImpl getCalculoRiesgoImplPort() {
        return super.getPort(new QName("http://jam.iplacex.cl/", "CalculoRiesgoImplPort"), CalculoRiesgoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculoRiesgoImpl
     */
    @WebEndpoint(name = "CalculoRiesgoImplPort")
    public CalculoRiesgoImpl getCalculoRiesgoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jam.iplacex.cl/", "CalculoRiesgoImplPort"), CalculoRiesgoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULORIESGOIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULORIESGOIMPLSERVICE_EXCEPTION;
        }
        return CALCULORIESGOIMPLSERVICE_WSDL_LOCATION;
    }

}
