
package cl.iplacex.jam.credito.wssoap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CalculoRiesgoImpl", targetNamespace = "http://jam.iplacex.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculoRiesgoImpl {


    /**
     * 
     * @param rut
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularRiesgo", targetNamespace = "http://jam.iplacex.cl/", className = "cl.iplacex.jam.credito.wssoap.CalcularRiesgo")
    @ResponseWrapper(localName = "calcularRiesgoResponse", targetNamespace = "http://jam.iplacex.cl/", className = "cl.iplacex.jam.credito.wssoap.CalcularRiesgoResponse")
    @Action(input = "http://jam.iplacex.cl/CalculoRiesgoImpl/calcularRiesgoRequest", output = "http://jam.iplacex.cl/CalculoRiesgoImpl/calcularRiesgoResponse")
    public String calcularRiesgo(
        @WebParam(name = "rut", targetNamespace = "")
        String rut);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarSolicitantes", targetNamespace = "http://jam.iplacex.cl/", className = "cl.iplacex.jam.credito.wssoap.ListarSolicitantes")
    @ResponseWrapper(localName = "listarSolicitantesResponse", targetNamespace = "http://jam.iplacex.cl/", className = "cl.iplacex.jam.credito.wssoap.ListarSolicitantesResponse")
    @Action(input = "http://jam.iplacex.cl/CalculoRiesgoImpl/listarSolicitantesRequest", output = "http://jam.iplacex.cl/CalculoRiesgoImpl/listarSolicitantesResponse")
    public String listarSolicitantes();

}
